# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket                 = "terraform-state-kb-trueidc"
    dynamodb_table         = "terraform-dynamodb-lockid-kb-trueidc"
    encrypt                = true
    key                    = "./terraform.tfstate"
    profile                = "terraform-poc-top"
    region                 = "ap-southeast-7"
    skip_region_validation = true
  }
}
